trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/my-artifact-$(Build.BuildId).zip'  # Dynamically name the zip file

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'my-artifact'  # The artifact name doesn't need the build ID anymore
    publishLocation: 'container'  # Publish artifacts under the "Artifacts" tab

- script: echo "Pipeline completed successfully."
  displayName: 'Print Success Message'
