trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/my-artifact-$(Build.BuildId).zip'  # Dynamically name the zip file

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'my-artifact'  # The artifact name doesn't need the build ID anymore

- task: Email@2
  inputs:
    to: 'your-email@example.com'  # Replace with your email address
    subject: 'Azure Pipeline Failed'
    body: |
      The Azure Pipeline failed. Please check the pipeline logs for details.
    sendEmailForFailedTests: true
