name: Label & comment issues

# Define the events that trigger the workflow
on:
  issues:
    types: [reopened, opened, closed]
  pull_request:
    types: [opened]

# Specify the environment where the jobs will run
runs-on: ubuntu-latest

# Define the jobs that run in the workflow
jobs:
  # Job to label issues with the "issue" and "fix" labels and comment on new issues
  label_issues:
    permissions:
      issues: write
      pull_requests: write
    steps:
      - name: Attach label to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })

      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thanks for opening this issue! We'll take a look as soon as possible."

  # Job to comment on closed issues
  comment_on_closed_issue:
    name: Comment on closed issue
    permissions:
      issues: write
    if: github.event_name == 'closed'
    steps:
      - name: Comment on issue state change
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "The issue is now resolved."

  # Job to comment on the first pull request
  comment_on_first_pull_request:
    name: Comment on first pull request
    permissions:
      pull_requests: write
    if: github.event_name == 'pull_request'
    steps:
      - name: Comment on first pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Congratulations on opening your first pull request! 🎉"
