name: Label & comment issues

# This action will trigger when an issue is reopened, opened, or closed.
on:
  issues:
    types:
      - reopened
      - opened
      - closed
  pull_request:
    types:
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: attach label to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })

      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Thanks for opening this issue! We'll take a look as soon as possible."

  comment_on_closed_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event_name == 'closed'
    steps:
      - name: Comment on issue state change
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "The issue is now resolved."

  comment_on_first_pull_request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event_name == 'pull-request'
    steps:
      - name: Comment on first pull request
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Congratulations on opening your first pull request! 🎉"
